name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cache-cargo
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        path: target/release/deps
        restore-keys: ${{ runner.os }}-cargo
    - name: Fetch Dependencies
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: cargo fetch
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
